'use strict';
const success = require('./success');
const error = require('./error');
const unAuthorize = require('./unAuthorize');
const created = require('./created');
const conflict = require('./conflict');
const notFound = require('./notFound');
const badReq = require('./badReq');
const forbidden = require('./forbidden');
module.exports = { success, forbidden, error, unAuthorize, created, badReq, notFound, conflict };
